from enum import IntEnum


class MessageLength(IntEnum):
    BITMAP_LENGTH = 8
    MESSAGE_TYPE_LENGTH = 4
    MESSAGE_TYPE_LENGTH_HEX = MESSAGE_TYPE_LENGTH * 2
    FIRST_BITMAP_CAPACITY = 64
    SECOND_BITMAP_CAPACITY = FIRST_BITMAP_CAPACITY * 2
    FIRST_BITMAP_LENGTH_HEX = 16
    SECOND_BITMAP_LENGTH_HEX = FIRST_BITMAP_LENGTH_HEX * 2
