from enum import StrEnum


class ToolBarElements(StrEnum):
    FILE = "File"
    TOOLS = "Tools"
    SETTINGS = "Settings"
    HELP = "Help"
    OPEN = "Open"
    SAVE = "Save"
    SAVE_AS = "Save as"
    CURRENT_TAB = "Current tab"
    ALL_TABS = "All tabs"
    JSON = "JSON"
    INI = "INI"
    DUMP = "DUMP"
    CONSTRUCT_FIELD = "Construct field"
    REVERSAL = "Reversal"
    REVERSE = "Reverse"
    LAST = "Last"
    OTHER = "Other"
    SET_REVERSAL_FIELDS = "Set reversal fields"
    SPECIFICATION = "Specification"
    CONFIGURATION = "Configuration"
    DOCUMENTATION = "User reference guide"
    HOTKEYS = "Hotkeys"
    ABOUT = "About Signal"
    API = "API"
    START = "Start"
    STOP = "Stop"
    EXIT = "Exit"
    RECONNECT = "Reconnect"
    ACTIONS = "Actions"
    ECHO_TEST = "Echo-test"
    PRINT = "Print"
    CLOSE_TABS = "Close tabs"
    CLEAR_LOG = "Clear log"
    CLEAR_MESSAGE = "Clear"
    RESET_MESSAGE = "Reset"
    VALIDATE = "Validate"
    REPEAT = "Repeat"
    KEEP_ALIVE = "Keep alive"
    MAIN_MESSAGE = "Main message"
    MESSAGE = "Message"
    LICENSE = "License agreement"
