from typing import Final


BITMAP_LENGTH: Final[int] = 8
MESSAGE_TYPE_LENGTH: Final[int] = 4
MESSAGE_TYPE_LENGTH_HEX = MESSAGE_TYPE_LENGTH * 2
FIRST_BITMAP_CAPACITY: Final[int] = 64
SECOND_BITMAP_CAPACITY: Final[int] = FIRST_BITMAP_CAPACITY * 2
FIRST_BITMAP_LENGTH_HEX: Final[int] = 16
SECOND_BITMAP_LENGTH_HEX: Final[int] = FIRST_BITMAP_LENGTH_HEX * 2
