BITMAP_LENGTH: int = 8
MESSAGE_TYPE_LENGTH: int = 4
MESSAGE_TYPE_LENGTH_HEX = MESSAGE_TYPE_LENGTH * 2
FIRST_BITMAP_CAPACITY: int = 64
SECOND_BITMAP_CAPACITY: int = FIRST_BITMAP_CAPACITY * 2
FIRST_BITMAP_LENGTH_HEX: int = 16
SECOND_BITMAP_LENGTH_HEX: int = FIRST_BITMAP_LENGTH_HEX * 2
